### ISSUE TITLE
mkdocs.yml isn't mkdocs-pagelist-plugin?

### ISSUE THREAD

**Issue by toto-co** [alanpt/mkdocs-pagelist-plugin#1]
hi.
this plug-in is very great !
but mkdocs.yml plugin name isn't 'mkdocs-」pagelist-plugin'.
mkdocs serve say, plugin not found 'mkdocs-pagelist-plugin.
mkdocs.yml is name 'pagelist'?
because,access point name is 'pagelist'.

**Comment by alanpt** [comment]
Thanks for spotting that. I should have mentioned that. I will make note of it.

**Comment by toto-co** [comment]
That was good

**Comment by alanpt** [comment]
Done. Thanks again.
